name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        nim: [stable, 1.6.14]
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: iffy/install-nim@v3
      with:
        version: ${{ matrix.nim }}
    - name: Test
      run: nimble test -y
